"""exercicio 02 aula 04

Revision ID: 549a8dfee30f
Revises: ae20a16c7887
Create Date: 2026-01-08 19:44:39.350070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549a8dfee30f'
down_revision: Union[str, Sequence[str], None] = 'ae20a16c7887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        )

    op.execute(
        "UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL"
    )

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'updated_at',
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
