"""campos criado em e atualizado em na tabela todo

Revision ID: 65003abcd8ca
Revises: fcc8018eaf7a
Create Date: 2026-01-24 18:55:15.487629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65003abcd8ca'
down_revision: Union[str, Sequence[str], None] = 'fcc8018eaf7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos') as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        )

    op.execute(
        "UPDATE todos SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )
    op.execute(
        "UPDATE todos SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL"
    )

    with op.batch_alter_table('todos') as batch_op:
        batch_op.alter_column(
            'created_at',
            nullable=False
        )
        batch_op.alter_column(
            'updated_at',
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
